---
- name: Ensure base packages are installed
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - apache2-utils
      - ca-certificates
      - curl
      - gnupg
      - jq
      - software-properties-common
      - unzip
    state: present
    update_cache: true

- name: Ensure QEMU guest agent is installed on VMs
  ansible.builtin.apt:
    name: qemu-guest-agent
    state: present
  when: ansible_facts.virtualization_type != "lxc"

- name: Ensure timezone is configured
  community.general.timezone:
    name: "{{ timezone }}"

- name: Ensure qemu guest agent is enabled
  ansible.builtin.service:
    name: qemu-guest-agent
    enabled: true
    state: started
  when: ansible_facts.virtualization_type != "lxc"
