---
- name: Configure Proxmox host
  hosts: proxmox
  become: true
  vars:
    ansible_ssh_private_key_file: "~/.ssh/root@192.168.1.200"
  roles:
    - proxmox

- name: Bootstrap all guests
  hosts: all:!nix:!proxmox
  become: true
  pre_tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:
        timeout: 60
  roles:
    - common

- name: Configure AdGuard Home
  hosts: adguard
  become: true
  roles:
    - adguard

- name: Configure edge proxy and DDNS
  hosts: edge
  become: true
  roles:
    - tailscale
    - edge

- name: Configure LLDAP user directory
  hosts: lldap
  become: true
  roles:
    - lldap

- name: Configure Authelia authentication server
  hosts: authelia
  become: true
  roles:
    - authelia

- name: Configure qBittorrent VPN host
  hosts: qbittorrent_vpn
  become: true
  pre_tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:
        timeout: 60
  roles:
    - qbittorrent_vpn

- name: Configure media automation host
  hosts: arr
  become: true
  pre_tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:
        timeout: 60
  roles:
    - arr

- name: Configure Jellyfin host
  hosts: media
  become: true
  pre_tasks:
    - name: Wait for connection
      ansible.builtin.wait_for_connection:
        timeout: 60
  roles:
    - jellyfin

- name: Configure NixOS host
  hosts: nix
  gather_facts: false
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: "~/.ssh/root@192.168.1.200"
  roles:
    - nix_host
